repos:
      - repo: https://github.com/timothycrosley/isort
        rev: 5.6.4
        hooks:
              - id: isort
                args: ["--settings-path=python/cuspatial/setup.cfg"]
                files: python/cuspatial/.*
                exclude: __init__.py$
                types: [text]
                types_or: [python, cython]
      - repo: https://github.com/ambv/black
        rev: stable
        hooks:
              - id: black
      - repo: https://gitlab.com/pycqa/flake8
        rev: 3.7.7
        hooks:
              - id: flake8
      - repo: https://gitlab.com/pycqa/flake8
        rev: 3.7.7
        hooks:
              - id: flake8
                alias: flake8-cython
                name: flake8-cython
                args: ["--config=python/cuspatial/.flake8.cython"]
                types: [cython]
default_language_version:
      python: python3
